version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: jephmaniragaba/linka_backend:simplified
    restart: always
    container_name: laravel-app
    working_dir: /linka
    volumes:
      - ./linka_App_Backend:/linka
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:69wkfn0hdAOwb9uDjVLKAh6b5vhXDOhLJdDTZzrtK+I=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=linka-backend-mysql
      - DB_PORT=3306
      - DB_DATABASE=FeliProject
      - DB_USERNAME=root
      - DB_PASSWORD=123
    ports:
      - "80:80"
    depends_on:
      - mysql
      - mailpit
    command: bash -c "php artisan migrate --force && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: FeliProject
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
