name: Deploy Linka App Backend to Docker

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: List directory contents
      run: |
        ls -la
        ls -la Linka_App_Backend

    - name: Build and push Docker image
      working-directory: Linka_App_Backend
      run: |
        docker build -t jephmaniragaba/linka_backend:latest .
        docker push jephmaniragaba/linka_backend:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy the image to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.NEW_SERVER_HOST }}
        username: linka
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull jephmaniragaba/linka_backend:latest
          docker stop laravel-app || true
          docker rm laravel-app || true
          docker run -d --name laravel-app -p 80:80 jephmaniragaba/linka_backend:latest
